# Generated by Django 5.0.1 on 2024-01-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
